<?php
/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php
if( $block->isHomePage() ) {
?>
<div id="theme_task_bander_wrap" data-mage-init='{"Vaimo_ThemeTask/js/theme_task_banner": {}}'>
    <div class="banner">
        <div class="banner-img">
            <img src="/pub/media/bander/1.jpg" width="100%" height="460" alt="轮播图1">
        </div>
    </div>

    <div class="banner">
        <div class="banner-img">
            <img src="/pub/media/bander/2.jpg" width="100%" height="460" alt="轮播图2">
        </div>
    </div>

    <div class="banner">
        <div class="banner-img">
            <img src="/pub/media/bander/3.jpg" width="100%" height="460" alt="轮播图3">
        </div>
    </div>

    <div class="banner">
        <div class="banner-img">
            <img src="/pub/media/bander/4.jpg" width="100%" height="460" alt="轮播图4">
        </div>
    </div>

    <div class="banner">
        <div class="banner-img">
            <img src="/pub/media/bander/5.jpg" width="100%" height="460" alt="轮播图5">
        </div>
    </div>

    <div class="tab">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>

    <div class="prev"></div>
    <div class="next"></div>
</div>
<?php
}
